[package]
name = "InterestBPS"
edition = "2024.beta" 
license = "MIT"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]  
published-at = "0x121445327a1f10ae96cab3e8628e6517dfb8a7ec55d26685476f0a58da0c4880"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
interest_bps = "0x121445327a1f10ae96cab3e8628e6517dfb8a7ec55d26685476f0a58da0c4880"