[package]
name = "InterestBPS"
edition = "2024.beta" 
license = "MIT"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]  
published-at = "0xc91aace4ebab58e7bac8fca36e69918571ebac356b4e9f8aaf99a682421c28ec"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
interest_bps = "0xc91aace4ebab58e7bac8fca36e69918571ebac356b4e9f8aaf99a682421c28ec" 